"""Rótulos PT extraídos do painel legado — mesclados em server_field_labels."""
from __future__ import annotations

LEGACY_PT_LABELS: dict[str, str] = {
    "additional_args": "Additional Args",
    "admin_logging": "Admin logging",
    "admin_password": "Senha admin",
    "allow_cave_building_pve": "Construção em caverna (PvE)",
    "allow_crosshair": "Crosshair",
    "allow_custom_recipes": "Receitas customizadas",
    "allow_hide_damage_source": "Ocultar fonte de dano nos logs",
    "allow_hit_markers": "Hit markers",
    "allow_hud": "HUD habilitado",
    "allow_platform_saddle_multi_floors": "Allow platform saddle multi floors",
    "allow_pve_gamma": "Gamma PvE",
    "allow_pvp_gamma": "Gamma PvP",
    "allow_third_person_view": "Terceira pessoa",
    "allow_tribe_alliances": "Alianças entre tribos",
    "allow_tribe_war_cancel_pve": "Cancelar guerra tribal PvE",
    "allow_tribe_war_pve": "Guerra tribal PvE",
    "allow_unlimited_respecs": "Allow unlimited respecs",
    "alt_save_directory_name": "Alt Save Directory",
    "auto_destroy_old_structures_multiplier": "Auto Destroy Old Structures",
    "auto_pve_start_time": "Início PvE (s desde meia-noite)",
    "auto_pve_stop_time": "Fim PvE (s desde meia-noite)",
    "auto_pve_timer": "Auto PvE Timer",
    "auto_pve_use_system_time": "Usar hora do sistema",
    "auto_respawn_wild_dinos_interval": "Intervalo respawn (s)",
    "auto_restart_time": "Horário de reinício (HH:MM)",
    "auto_save_period": "Auto-save (min)",
    "auto_unlock_all_engrams": "Auto Unlock All Engrams",
    "auto_update_check_minutes": "Intervalo de verificação (min)",
    "ban_list_url": "URL da BanList",
    "base_temperature_multiplier": "Base Temperature",
    "branch_name": "Branch Name",
    "branch_password": "Branch Password",
    "clamp_item_spoiling_times": "Clamp Item Spoiling Times",
    "clamp_resource_harvest_damage": "Clamp Resource Harvest Damage",
    "cluster_dir_override": "Cluster Dir Override",
    "color": "Cor do card (hex, ex: #22c55e)",
    "crop_decay_speed_multiplier": "Crop Decay Speed",
    "crop_growth_speed_multiplier": "Crop Growth Speed",
    "cross_ark_allow_foreign_dino_downloads": "Permitir dinos de outros clusters",
    "cross_ark_cluster_id": "Cluster ID",
    "custom_recipe_effectiveness_multiplier": "Effectiveness multiplier",
    "custom_recipe_skill_multiplier": "Skill multiplier",
    "day_cycle_speed_scale": "Day Cycle Speed",
    "day_time_speed_scale": "Day Time Speed",
    "destroy_unconnected_water_pipes": "Destroy Unconnected Water Pipes",
    "difficulty_offset": "DifficultyOffset",
    "disable_friendly_fire_pve": "Sem fogo amigo PvE",
    "disable_friendly_fire_pvp": "Sem fogo amigo PvP",
    "disable_loot_crates": "Desativar Loot Crates",
    "disable_structure_placement_collision": "Disable Structure Placement Collision",
    "disable_weather_fog": "Disable Weather Fog",
    "discord_notify_player_join": "Jogador entrou (join)",
    "discord_notify_player_leave": "Jogador saiu (leave)",
    "discord_notify_server_start": "Servidor iniciado",
    "discord_notify_server_stop": "Servidor parado",
    "discord_webhook_url": "URL do Webhook",
    "enable_auto_respawn_wild_dinos": "Forçar respawn dinos selvagens",
    "enable_auto_restart": "Habilitar reinício automático",
    "enable_auto_update_check": "Verificar atualizações automaticamente",
    "enable_ban_list_url": "Usar BanList URL",
    "enable_difficulty_override": "Override dificuldade oficial",
    "enable_diseases": "Doenças habilitadas",
    "enable_extinction_event": "Evento de extinção",
    "enable_extra_structure_prevention_volumes": "Extra Structure Prevention Volumes",
    "enable_fast_decay_interval": "Enable Fast Decay Interval",
    "enable_hardcore": "Hardcore",
    "enable_kick_idle_players": "Kickar ociosos",
    "enable_pvp": "PvP habilitado",
    "enable_structure_decay_pve": "Enable Structure Decay PvE",
    "enable_tribute_downloads": "Permitir downloads de tributo",
    "exclusive_join": "Exclusive Join (somente whitelist)",
    "extinction_event_interval": "Intervalo extinção (s)",
    "fast_decay_interval": "Fast Decay Interval (s)",
    "fast_decay_unsnapped_core_structures": "Fast Decay Unsnapped Core Structures",
    "fishing_loot_quality_multiplier": "Fishing loot quality",
    "flyer_platform_allow_unaligned_dino_basing": "Flyer Platform Allow Unaligned Dino Basing",
    "force_all_structure_locking": "Force All Structure Locking",
    "global_corpse_decomposition_multiplier": "Corpse Decomposition Time",
    "global_item_decomposition_multiplier": "Item Decomposition Time",
    "global_powered_battery_durability_decrease": "Battery durability decrease/s",
    "global_spoiling_time_multiplier": "Global Spoiling Time",
    "global_voice_chat": "Voice chat global",
    "hair_growth_speed_multiplier": "Hair Growth Speed",
    "hard_limit_turrets_in_range": "Hard Limit Turrets In Range",
    "harvest_amount_multiplier": "Harvest Amount",
    "harvest_health_multiplier": "Harvest Health",
    "increase_pvp_respawn_interval": "Aumentar intervalo PvP respawn",
    "install_dir": "Pasta de instalação",
    "kick_idle_players": "Período idle kick (s)",
    "lay_egg_interval_multiplier": "Lay Egg Interval",
    "limit_turrets_in_range": "Limit Turrets In Range",
    "limit_turrets_num": "Turrets Num",
    "limit_turrets_range": "Turrets Range",
    "max_alliances_per_tribe": "Max alianças por tribo",
    "max_platform_saddle_structures": "Max Platform Saddle Structures",
    "max_players": "Max jogadores",
    "max_structures_in_range": "Max Structures In Range",
    "max_tribe_logs": "Max tribe logs",
    "max_tribe_size": "Max membros na tribo",
    "max_tribes_per_alliance": "Max tribos por aliança",
    "min_dino_reupload_interval": "Min dino reupload interval (s)",
    "motd_duration": "Duração MOTD (s)",
    "name": "Nome no gerenciador",
    "night_time_speed_scale": "Night Time Speed",
    "non_permanent_diseases": "Doenças não permanentes",
    "notify_discord_on_events": "Notificar via Discord em eventos",
    "npc_stasis_range_scale_end": "Player count end",
    "npc_stasis_range_scale_percent_end": "Percent end",
    "npc_stasis_range_scale_start": "Player count start",
    "only_allow_specified_engrams": "Only Allow Specified Engrams",
    "only_auto_destroy_core_structures": "Only Auto Destroy Core Structures",
    "only_decay_unsnapped_core_structures": "Only Decay Unsnapped Core Structures",
    "override_npc_stasis_range_scale": "Override NPC Stasis Range Scale",
    "override_official_difficulty": "OverrideOfficialDifficulty",
    "override_structure_platform_prevention": "Override Structure Platform Prevention",
    "oxygen_swim_speed_stat_multiplier": "Oxygen swim speed stat multiplier",
    "passive_defenses_damage_riderless_dinos": "Passive Defenses Damage Riderless Dinos",
    "per_platform_max_structures_multiplier": "Per Platform Max Structures",
    "pgm_enabled": "Habilitar ARK Procedural",
    "pgm_name": "Nome do mapa",
    "player_joined_notifications": "Notificar entrada (join)",
    "player_leave_notifications": "Notificar saída (leave)",
    "poop_interval_multiplier": "Poop Interval",
    "prevent_download_dinos": "Bloquear download dinos",
    "prevent_download_items": "Bloquear download items",
    "prevent_download_survivors": "Bloquear download survivors",
    "prevent_pvp_offline": "Prevenir PvP offline",
    "prevent_pvp_offline_interval": "Intervalo offline (s)",
    "prevent_pvp_offline_invincible_interval": "Invincible interval (s)",
    "prevent_spawn_animations": "Prevent spawn animations",
    "prevent_upload_dinos": "Bloquear upload dinos",
    "prevent_upload_items": "Bloquear upload items",
    "prevent_upload_survivors": "Bloquear upload survivors",
    "proximity_chat": "Proximity chat",
    "pve_allow_structures_at_supply_drops": "PvE Allow Structures At Supply Drops",
    "pve_structure_decay_destruction_period": "PvE Structure Decay Destruction",
    "pve_structure_decay_period_multiplier": "PvE Structure Decay Period",
    "pvp_respawn_base_amount": "Base amount",
    "pvp_respawn_check_period": "Check period (s)",
    "pvp_respawn_multiplier": "Respawn multiplier",
    "pvp_structure_decay": "PvP Structure Decay",
    "pvp_zone_structure_damage_multiplier": "PvP Zone Structure Damage",
    "query_port": "Porta (query)",
    "random_supply_crate_points": "Random supply crate points",
    "rcon_enabled": "Habilitar RCON",
    "rcon_log_buffer": "Buffer log RCON",
    "rcon_port": "Porta RCON",
    "resource_no_replenish_radius_players": "No Replenish Radius (Players)",
    "resource_no_replenish_radius_structures": "No Replenish Radius (Structures)",
    "resources_respawn_multiplier": "Resources Respawn",
    "restart_countdown_minutes": "Contagem regressiva (min)",
    "save_min_dino_reupload_interval": "Intervalo mínimo de re-upload de dinos",
    "save_tribute_char_expiration": "Salvar expiração de personagens",
    "save_tribute_dino_expiration": "Salvar expiração de dinos",
    "save_tribute_item_expiration": "Salvar expiração de items",
    "server_password": "Senha do servidor",
    "server_port": "Porta (game)",
    "session_name": "Nome da sessão",
    "show_floating_damage_text": "Floating damage text",
    "show_map_player_location": "Mostrar posição no mapa",
    "spectator_password": "Senha spectator",
    "structure_damage_multiplier": "Structure Damage",
    "structure_damage_repair_cooldown": "Damage Repair Cooldown (s)",
    "structure_resistance_multiplier": "Structure Resistance",
    "supply_crate_loot_quality_multiplier": "Supply crate loot quality",
    "total_conversion_mod_id": "Total Conversion Mod ID",
    "tribe_log_destroyed_enemy_structures": "Log estruturas destruídas por inimigos",
    "tribe_name_change_cooldown": "Cooldown mudança de nome (s)",
    "tribute_char_expiration_seconds": "Expiração personagem (s)",
    "tribute_dino_expiration_seconds": "Expiração dinos (s)",
    "tribute_item_expiration_seconds": "Expiração items (s)",
    "use_corpse_life_span_multiplier": "Corpse life span multiplier",
    "use_corpse_locator": "Corpse locator",
    "use_optimized_harvesting_health": "Use Optimized Harvesting Health",
}
